// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5q6NGDHtAywbzXOAHG21IpemhQc2JBuw',
    appId: '1:291538833230:web:221b3e8472566c1a01581f',
    messagingSenderId: '291538833230',
    projectId: 'tartanhacks25-huddleup',
    authDomain: 'tartanhacks25-huddleup.firebaseapp.com',
    storageBucket: 'tartanhacks25-huddleup.firebasestorage.app',
    measurementId: 'G-6FN7W4989J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOjkEpHGhHlzHTFYqhGqNGv0fZUZij-v8',
    appId: '1:291538833230:android:063c6e9bb5e7234b01581f',
    messagingSenderId: '291538833230',
    projectId: 'tartanhacks25-huddleup',
    storageBucket: 'tartanhacks25-huddleup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1usQpP1e17dI6yyQUN7N50Bt57Lf4TYw',
    appId: '1:291538833230:ios:0c2d6e34d640896a01581f',
    messagingSenderId: '291538833230',
    projectId: 'tartanhacks25-huddleup',
    storageBucket: 'tartanhacks25-huddleup.firebasestorage.app',
    iosBundleId: 'com.example.tartanhacks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1usQpP1e17dI6yyQUN7N50Bt57Lf4TYw',
    appId: '1:291538833230:ios:0c2d6e34d640896a01581f',
    messagingSenderId: '291538833230',
    projectId: 'tartanhacks25-huddleup',
    storageBucket: 'tartanhacks25-huddleup.firebasestorage.app',
    iosBundleId: 'com.example.tartanhacks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5q6NGDHtAywbzXOAHG21IpemhQc2JBuw',
    appId: '1:291538833230:web:47ae5c936609e1d801581f',
    messagingSenderId: '291538833230',
    projectId: 'tartanhacks25-huddleup',
    authDomain: 'tartanhacks25-huddleup.firebaseapp.com',
    storageBucket: 'tartanhacks25-huddleup.firebasestorage.app',
    measurementId: 'G-9S6KCYJV9P',
  );
}
