// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzvk_Lo55j6UriMasYeJ8j_rcSQpNvytQ',
    appId: '1:975572012603:web:eb07432021001f20f3d61e',
    messagingSenderId: '975572012603',
    projectId: 'teamify-ce52e',
    authDomain: 'teamify-ce52e.firebaseapp.com',
    storageBucket: 'teamify-ce52e.firebasestorage.app',
    measurementId: 'G-5THJK3CQHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfKqEekvJ8fp1iVOs-UIYR4JAvHLOAeNg',
    appId: '1:975572012603:android:8e113f5605e5b40cf3d61e',
    messagingSenderId: '975572012603',
    projectId: 'teamify-ce52e',
    storageBucket: 'teamify-ce52e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNpuO_7mzxefKg4fsS-35OOUvAiWuDuHM',
    appId: '1:975572012603:ios:56443806d19443a9f3d61e',
    messagingSenderId: '975572012603',
    projectId: 'teamify-ce52e',
    storageBucket: 'teamify-ce52e.firebasestorage.app',
    iosBundleId: 'com.example.tartanhacks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNpuO_7mzxefKg4fsS-35OOUvAiWuDuHM',
    appId: '1:975572012603:ios:56443806d19443a9f3d61e',
    messagingSenderId: '975572012603',
    projectId: 'teamify-ce52e',
    storageBucket: 'teamify-ce52e.firebasestorage.app',
    iosBundleId: 'com.example.tartanhacks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzvk_Lo55j6UriMasYeJ8j_rcSQpNvytQ',
    appId: '1:975572012603:web:61555bfe7f95100ef3d61e',
    messagingSenderId: '975572012603',
    projectId: 'teamify-ce52e',
    authDomain: 'teamify-ce52e.firebaseapp.com',
    storageBucket: 'teamify-ce52e.firebasestorage.app',
    measurementId: 'G-LDXK1V1T60',
  );
}
